//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public int anime_id { get; set; }
        public string name { get; set; }
        public string genre { get; set; }
        public string type { get; set; }
        public Nullable<double> episodes { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<double> members { get; set; }
    }
}
