//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spotify
    {
        public int Index { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public string Top_Genre { get; set; }
        public Nullable<double> Year { get; set; }
        public Nullable<double> Beats_Per_Minute { get; set; }
        public Nullable<double> Energy { get; set; }
        public Nullable<double> Danceability { get; set; }
        public Nullable<double> Loudness { get; set; }
        public Nullable<double> Liveness { get; set; }
        public Nullable<double> Valence { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> Acousticness { get; set; }
        public Nullable<double> Speechiness { get; set; }
        public Nullable<double> Popularity { get; set; }
    }
}
